version: '3.9'

services:
  db:
    image: mysql:8.0.30
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      - MYSQL_USER=damagedetection
      - MYSQL_PASSWORD=pw
      - MYSQL_DATABASE=damagedetection
      - MYSQL_ROOT_PASSWORD=pw
    command: --lower_case_table_names=1
    cap_add:
      - SYS_NICE
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - damagedetection

volumes:
  dbdata:

networks:
  damagedetection:
    external: false
    name: damagedetection


